### ISSUE TITLE
Config file doesn't work?

### ISSUE THREAD

**Issue by jeroenkampinga** [jsxtools/rescript-use-postcss-config#1]
In my .rescriptsrc.js file I have the following:
```
module.exports = [
  ['use-postcss-config'],
  ['use-eslint-config', '.eslintrc.js'],
  ['use-babel-config', '.babelrc.js'],
];
```

In my postcss.config.js file I have: 
```
const pxToRem = require('postcss-pxtorem');
const autoprefixer = require('autoprefixer');

module.exports = {
  plugins: [
    autoprefixer({
      grid: true,
    }),
    pxToRem({ propList: ['*'], rootValue: 19, minPixelValue: 4 }),
  ],
};
```

But in my build .css file I never get the grid prefixes or rem values. I've also tried to rename the file to .postcssrc.js but it didn't help.

Do I need to do anything else to enable the plugin?

**Comment by jeroenkampinga** [comment]
Issue was not related to the rescript-use-postcss-config module.

**Comment by Hitotsubashi** [comment]
> Issue was not related to the rescript-use-postcss-config module.

I meet the same question ,and I want to know how did you solve it.
